improve openmediavault help
tuna/mirror-web pull request #254
Opened 2021-03-21 01:00 UTC by septs

2021-03-21 05:05 UTC, ZenithalHourlyRate commented
注意到 https://github.com/openmediavault/openmediavault/pull/988 还未合并，应将该PR标注为草稿。同时由于该特性较新，似乎需要在帮助文本中提醒用户升级 `omv-salt` 工具

2021-03-21 05:10 UTC, ZenithalHourlyRate commented on help/_posts/1970-01-01-openmediavault.md
> +# deb https://{{ site.hostname }}/OpenMediaVault/public usul partner
注意到这里都是 `/OpenMediaVault/public` 的内容，但在 https://openmediavault.readthedocs.io/en/latest/installation/on_debian.html 中有 `openmediavault/packages` 的内容，是否需要添加 `packages` 部分？或者说这两者没有差别？

另：对于 packages 和 openmediavault-plugin-developers 同步较为过时的问题，可以在 tuna/issues 中提出

2021-03-21 12:45 UTC, ZenithalHourlyRate requested changes

2021-03-21 12:45 UTC, ZenithalHourlyRate commented on help/_posts/1970-01-01-openmediavault.md
> +1. 由于 Open Media Vault 自带 kernel backports 因此在 `/etc/apt/source.list` 中配置 backports 源会造成冲突。
自带 kernel backports 但又在帮助文档上方配置了 `OMV_APT_KERNEL_BACKPORTS_REPOSITORY_URL "https://{{ site.hostname }}/debian`，没太看懂这个冲突点在哪；`omv-salt stage run all` 写的文件不是 `/etc/apt/source.list` 吗

2021-03-21 12:45 UTC, ZenithalHourlyRate commented on help/_posts/1970-01-01-openmediavault.md
> +2. 由于 Open Media Vault 的公钥分发通过源自己携带完成，因此本身存在被篡改的可能性。
这句话缺少上下文，告诉用户 `通过源分发可能会被篡改` 后应该给一些指导?

2021-03-21 12:45 UTC, ZenithalHourlyRate commented on help/_posts/1970-01-01-openmediavault.md
> +deb https://{{ site.hostname }}/OpenMediaVault/packages usul partner
注意到官方帮助中默认将 `usul-proposed` 与 `usul partner` 注释掉，应该是让用户有需求时在自行取消注释，而不是默认启用所有源，所以这里应该与官方的风格一致

2021-03-21 12:51 UTC, septs commented on help/_posts/1970-01-01-openmediavault.md
> +1. 由于 Open Media Vault 自带 kernel backports 因此在 `/etc/apt/source.list` 中配置 backports 源会造成冲突。
不是

```
$ ls /etc/apt/sources.list.d 
omvextras.list  openmediavault-os-security.list  openmediavault.list
```

2021-03-21 12:52 UTC, septs commented on help/_posts/1970-01-01-openmediavault.md
> +1. 由于 Open Media Vault 自带 kernel backports 因此在 `/etc/apt/source.list` 中配置 backports 源会造成冲突。
如果在 OMV 面板中开启 backports 则会生成相应的文件。

2021-03-21 12:53 UTC, septs commented on help/_posts/1970-01-01-openmediavault.md
> +2. 由于 Open Media Vault 的公钥分发通过源自己携带完成，因此本身存在被篡改的可能性。
@z4yx 建议我写上的，原话为
```
septs, [21.03.21 09:58]
但是你得吧他的 asc 一起拉过去（因为他整个 base 都改过去了

Deteled Account, [21.03.21 09:59]
行吧，这样要在help里提醒用户自己承担安全风险
```

2021-03-21 12:57 UTC, septs commented on help/_posts/1970-01-01-openmediavault.md
> +1. 由于 Open Media Vault 自带 kernel backports 因此在 `/etc/apt/source.list` 中配置 backports 源会造成冲突。
```
$ ls -la /etc/apt/sources.list.d
total 16K
-rw-r--r-- 1 root root 451 Mar 21 11:34 omvextras.list
-rw-r--r-- 1 root root  87 Mar 21 12:55 openmediavault-kernel-backports.list
-rw-r--r-- 1 root root 192 Mar 21 12:55 openmediavault-os-security.list
-rw-r--r-- 1 root root 625 Mar 21 11:34 openmediavault.list
$ cat /etc/apt/sources.list.d/openmediavault-kernel-backports.list 
deb https://mirrors.tuna.tsinghua.edu.cn/debian buster-backports main contrib non-free
```

为了验证，这是的生成逻辑我已经调整过了

2021-03-21 12:58 UTC, ZenithalHourlyRate commented on help/_posts/1970-01-01-openmediavault.md
> +2. 由于 Open Media Vault 的公钥分发通过源自己携带完成，因此本身存在被篡改的可能性。
嗯……所以用户不可避免地得用这个镜像站提供的公钥吗，有啥措施避免吗，或者没法避免?（这是缺少下文）

然后为什么会有这个问题（换用镜像以后公钥是从镜像获取的）感觉得说明一下（这是缺少上文）

2021-03-21 13:00 UTC, septs commented on help/_posts/1970-01-01-openmediavault.md
> +2. 由于 Open Media Vault 的公钥分发通过源自己携带完成，因此本身存在被篡改的可能性。
具体为 https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-omvextrasorg/commit/1e63392e413186c95f61dde9d265508d9fc1a7a6#

2021-03-21 13:01 UTC, ZenithalHourlyRate commented on help/_posts/1970-01-01-openmediavault.md
> +# deb https://{{ site.hostname }}/OpenMediaVault/packages usul partner
官方给的这一大段都是被注释掉的，只保留了 `public usul main`，在镜像帮助中默认启用这些源是否有必要?

2021-03-21 13:15 UTC, ZenithalHourlyRate approved these changes
Will merge after https://github.com/openmediavault/openmediavault/pull/988

2021-03-22 05:33 UTC, septs commented on help/_posts/1970-01-01-openmediavault.md
> +omv-env set OMV_PROXMOX_APT_REPOSITORY_URL "https://{{ site.hostname }}/proxmox/debian"
https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-omvextrasorg/pull/53

2021-03-22 05:45 UTC, ZenithalHourlyRate approved these changes

2021-03-23 06:24 UTC, merged